/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : ADC.h
**     Project     : TPPFC_MC56F82748_V1.0
**     Processor   : MC56F82748VLH
**     Component   : Init_ADC
**     Version     : Component 01.000, Driver 01.00, CPU db: 3.50.001
**     Compiler    : CodeWarrior DSP C Compiler
**     Date/Time   : 2022-01-24, 16:51, # CodeGen: 0
**     Abstract    :
**          This file implements the ADC (ADC) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : ADC
**          Device                                         : ADC
**          Settings                                       : 
**            Clock setting                                : 
**              Clock divisor select value                 : divide by 5
**              ADC frequency                              : 10 MHz
**              Clock divisor select value 1               : divide by 5
**              ADC frequency 1                            : 10 MHz
**              Power-up delay                             : 26
**              Power-up delay                             : 2.600 us
**            Stop mode (0)                                : no
**            Stop mode 1                                  : yes
**            ADC mode                                     : Triggered parallel
**            Parallel mode                                : Simultaneous
**            Trigger mode (0)                             : SYNC input or START bit
**            Trigger mode 1                               : SYNC input or START bit
**            DMA trigger source                           : EOSI
**            Differential/Single ended mode               : 
**              ANA0-ANA1                                  : Differential mode
**              ANA2-ANA3                                  : Single ended mode
**              ANB0-ANB1                                  : Single ended mode
**              ANB2-ANB3                                  : Single ended mode
**              ANA4-ANA5                                  : Single ended mode
**              ANA6-ANA7                                  : Single ended mode
**              ANB4-ANB5                                  : Single ended mode
**              ANB6-ANB7                                  : Single ended mode
**            Unipolar/Differential mode                   : 
**              ANA0-ANA1                                  : Fully Differential mode
**              ANA2-ANA3                                  : Fully Differential mode
**              ANB0-ANB1                                  : Fully Differential mode
**              ANB2-ANB3                                  : Fully Differential mode
**              ANA4-ANA5                                  : Fully Differential mode
**              ANA6-ANA7                                  : Fully Differential mode
**              ANB4-ANB5                                  : Fully Differential mode
**              ANB6-ANB7                                  : Fully Differential mode
**            Gain control                                 : 
**              ANA0                                       : x1 amplification
**              ANA1                                       : x1 amplification
**              ANA2                                       : x1 amplification
**              ANA3                                       : x1 amplification
**              ANA4                                       : x1 amplification
**              ANA5                                       : x1 amplification
**              ANA6                                       : x1 amplification
**              ANA7                                       : x1 amplification
**              ANB0                                       : x1 amplification
**              ANB1                                       : x1 amplification
**              ANB2                                       : x1 amplification
**              ANB3                                       : x1 amplification
**              ANB4                                       : x1 amplification
**              ANB5                                       : x1 amplification
**              ANB6                                       : x1 amplification
**              ANB7                                       : x1 amplification
**              Alternative input 0                        : x1 amplification
**              Alternative input 1                        : x1 amplification
**              Alternative input 2                        : x1 amplification
**              Alternative input 3                        : x1 amplification
**            Sample enable                                : 
**              Sample 0                                   : Enabled
**              Sample 1                                   : Enabled
**              Sample 2                                   : Disabled
**              Sample 3                                   : Disabled
**              Sample 4                                   : Disabled
**              Sample 5                                   : Disabled
**              Sample 6                                   : Disabled
**              Sample 7                                   : Disabled
**              Sample 8                                   : Enabled
**              Sample 9                                   : Enabled
**              Sample 10                                  : Disabled
**              Sample 11                                  : Disabled
**              Sample 12                                  : Disabled
**              Sample 13                                  : Disabled
**              Sample 14                                  : Disabled
**              Sample 15                                  : Disabled
**              Sample 16                                  : Disabled
**              Sample 17                                  : Disabled
**              Sample 18                                  : Disabled
**              Sample 19                                  : Disabled
**            Channel to sample mapping                    : 
**              Sample 0                                   : ANA0
**              Sample 1                                   : ANA4
**              Sample 2                                   : ANA2
**              Sample 3                                   : ANA3
**              Sample 4                                   : ANA4
**              Sample 5                                   : ANA5
**              Sample 6                                   : ANA6
**              Sample 7                                   : ANA7
**              Sample 8                                   : ANB0
**              Sample 9                                   : ANB0
**              Sample 10                                  : ANB2
**              Sample 11                                  : ANB3
**              Sample 12                                  : ANB4
**              Sample 13                                  : ANB5
**              Sample 14                                  : ANB6
**              Sample 15                                  : ANB7
**              Sample 16                                  : Alternative input 0
**              Sample 17                                  : Alternative input 1
**              Sample 18                                  : Alternative input 2
**              Sample 19                                  : Alternative input 3
**            Zero crossing                                : 
**              Sample 0                                   : Disabled
**              Sample 1                                   : Disabled
**              Sample 2                                   : Disabled
**              Sample 3                                   : Disabled
**              Sample 4                                   : Disabled
**              Sample 5                                   : Disabled
**              Sample 6                                   : Disabled
**              Sample 7                                   : Disabled
**              Sample 8                                   : Disabled
**              Sample 9                                   : Disabled
**              Sample 10                                  : Disabled
**              Sample 11                                  : Disabled
**              Sample 12                                  : Disabled
**              Sample 13                                  : Disabled
**              Sample 14                                  : Disabled
**              Sample 15                                  : Disabled
**              Sample 16                                  : Disabled
**              Sample 17                                  : Disabled
**              Sample 18                                  : Disabled
**              Sample 19                                  : Disabled
**            Low limit                                    : 
**              Sample 0                                   : 0
**              Sample 1                                   : 0
**              Sample 2                                   : 0
**              Sample 3                                   : 0
**              Sample 4                                   : 0
**              Sample 5                                   : 0
**              Sample 6                                   : 0
**              Sample 7                                   : 0
**              Sample 8                                   : 0
**              Sample 9                                   : 0
**              Sample 10                                  : 0
**              Sample 11                                  : 0
**              Sample 12                                  : 0
**              Sample 13                                  : 0
**              Sample 14                                  : 0
**              Sample 15                                  : 0
**              Sample 16                                  : 0
**              Sample 17                                  : 0
**              Sample 18                                  : 0
**              Sample 19                                  : 0
**            High limit                                   : 
**              Sample 0                                   : 32760
**              Sample 1                                   : 32760
**              Sample 2                                   : 32760
**              Sample 3                                   : 32760
**              Sample 4                                   : 32760
**              Sample 5                                   : 32760
**              Sample 6                                   : 32760
**              Sample 7                                   : 32760
**              Sample 8                                   : 32760
**              Sample 9                                   : 32760
**              Sample 10                                  : 32760
**              Sample 11                                  : 32760
**              Sample 12                                  : 32760
**              Sample 13                                  : 32760
**              Sample 14                                  : 32760
**              Sample 15                                  : 32760
**              Sample 16                                  : 32760
**              Sample 17                                  : 32760
**              Sample 18                                  : 32760
**              Sample 19                                  : 32760
**            Offset                                       : 
**              Sample 0                                   : 0
**              Sample 1                                   : 0
**              Sample 2                                   : 0
**              Sample 3                                   : 0
**              Sample 4                                   : 0
**              Sample 5                                   : 0
**              Sample 6                                   : 0
**              Sample 7                                   : 0
**              Sample 8                                   : 4000
**              Sample 9                                   : 0
**              Sample 10                                  : 0
**              Sample 11                                  : 0
**              Sample 12                                  : 0
**              Sample 13                                  : 0
**              Sample 14                                  : 0
**              Sample 15                                  : 0
**              Sample 16                                  : 0
**              Sample 17                                  : 0
**              Sample 18                                  : 0
**              Sample 19                                  : 0
**            Scan control                                 : 
**              Sample 0                                   : Continue
**              Sample 1                                   : Continue
**              Sample 2                                   : Continue
**              Sample 3                                   : Continue
**              Sample 4                                   : Continue
**              Sample 5                                   : Continue
**              Sample 6                                   : Continue
**              Sample 7                                   : Continue
**              Sample 8                                   : Continue
**              Sample 9                                   : Continue
**              Sample 10                                  : Continue
**              Sample 11                                  : Continue
**              Sample 12                                  : Continue
**              Sample 13                                  : Continue
**              Sample 14                                  : Continue
**              Sample 15                                  : Continue
**              Sample 16                                  : Continue
**              Sample 17                                  : Continue
**              Sample 18                                  : Continue
**              Sample 19                                  : Continue
**            Source of ANA6 input                         : AN
**            Source of ANA7 input                         : AN
**            Source of ANB6 input                         : AN
**            Source of ANB7 input                         : AN
**            High volt. ref. source 0                     : internal
**            Low volt. ref. source 0                      : internal
**            High volt. ref. source 1                     : internal
**            Low volt. ref. source 1                      : internal
**            Auto power-down                              : Disabled
**            Auto standby                                 : Disabled
**          Pins                                           : 
**            ANA0                                         : Enabled
**              Pin                                        : GPIOA0/ANA0/CMPA_IN3/CMPC_O
**              Pin signal                                 : 
**            ANA1                                         : Enabled
**              Pin                                        : GPIOA1/ANA1/CMPA_IN0
**              Pin signal                                 : 
**            ANA2                                         : Disabled
**            ANA3                                         : Disabled
**            ANA4                                         : Enabled
**              Pin                                        : GPIOA4/ANA4/CMPD_IN0
**              Pin signal                                 : 
**            ANA5                                         : Disabled
**            ANA6                                         : Disabled
**            ANA7                                         : Disabled
**            ANB0                                         : Enabled
**              Pin                                        : GPIOB0/ANB0/CMPB_IN3
**              Pin signal                                 : 
**            ANB1                                         : Disabled
**            ANB2                                         : Enabled
**              Pin                                        : GPIOB2/ANB2/VREFHB/CMPC_IN3
**              Pin signal                                 : 
**            ANB3                                         : Disabled
**            ANB4                                         : Disabled
**            ANB5                                         : Disabled
**            ANB6                                         : Disabled
**            ANB7                                         : Disabled
**            Alternative input 0                          : Disabled
**            Alternative input 1                          : Disabled
**            Alternative input 2                          : Disabled
**            Alternative input 3                          : Disabled
**            SYNC0                                        : Enabled
**              Pin                                        : PWM2_TRG0
**              Pin signal                                 : 
**            SYNC1                                        : Disabled
**            High volt. ref. pin 0                        : Disabled
**            Low volt. ref. pin 0                         : Disabled
**            High volt. ref. pin 1                        : Disabled
**            Low volt. ref. pin 1                         : Disabled
**          Interrupts                                     : 
**            Conversion complete (0)                      : 
**              Interrupt                                  : INT_ADC_CC0
**              Interrupt priority                         : disabled
**              ISR Name                                   : 
**              End of scan interrupt                      : Disabled
**              DMA request                                : Disabled
**            Conversion complete 1                        : 
**              Interrupt                                  : INT_ADC_CC1
**              Interrupt priority                         : disabled
**              ISR Name                                   : 
**              End of scan interrupt                      : Disabled
**              DMA request                                : Disabled
**            Scan halted interrupt enable                 : 
**              Sample 0                                   : Disabled
**              Sample 1                                   : Disabled
**              Sample 2                                   : Disabled
**              Sample 3                                   : Disabled
**              Sample 4                                   : Disabled
**              Sample 5                                   : Disabled
**              Sample 6                                   : Disabled
**              Sample 7                                   : Disabled
**              Sample 8                                   : Disabled
**              Sample 9                                   : Disabled
**              Sample 10                                  : Disabled
**              Sample 11                                  : Disabled
**              Sample 12                                  : Disabled
**              Sample 13                                  : Disabled
**              Sample 14                                  : Disabled
**              Sample 15                                  : Disabled
**              Sample 16                                  : Disabled
**              Sample 17                                  : Disabled
**              Sample 18                                  : Disabled
**              Sample 19                                  : Disabled
**            Zero crossing or limit error                 : 
**              Interrupt                                  : INT_ADC_ERR
**              Interrupt priority                         : disabled
**              ISR Name                                   : 
**              Zero crossing interrupt                    : Disabled
**              Low Limit Error Interrupt                  : Disabled
**              High Limit Error Interrupt                 : Disabled
**          Initialization                                 : 
**            Power Down ADC 0                             : No
**            Power Down ADC 1                             : No
**            Enable peripheral clock                      : yes
**            Call Init method                             : yes
**            Utilize after reset values                   : default
**     Contents    :
**         Init - void ADC_Init(void);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file ADC.h
** @version 01.00
** @brief
**          This file implements the ADC (ADC) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
*/         
/*!
**  @addtogroup ADC_module ADC module documentation
**  @{
*/         

#ifndef ADC_H_
#define ADC_H_

/* MODULE ADC. */

#include "ADC_Init.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Initialization method user name */
#define ADC_Init ADC_Init
/* PDD macros peripheral base address parameter */
#define ADC_DEVICE ADC_BASE_PTR

#ifdef __cplusplus
}
#endif

/* END ADC. */
#endif /* #ifndef __ADC_H_ */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
