/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : ADC_Config.h
**     Project     : TPPFC_MC56F82748_V1.0
**     Processor   : MC56F82748VLH
**     Component   : Init_ADC
**     Version     : Component 01.000, Driver 01.00, CPU db: 3.50.001
**     Compiler    : CodeWarrior DSP C Compiler
**     Date/Time   : 2022-01-24, 16:51, # CodeGen: 0
**     Abstract    :
**          This file implements the ADC (ADC) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : ADC
**          Device                                         : ADC
**          Settings                                       : 
**            Clock setting                                : 
**              Clock divisor select value                 : divide by 5
**              ADC frequency                              : 10 MHz
**              Clock divisor select value 1               : divide by 5
**              ADC frequency 1                            : 10 MHz
**              Power-up delay                             : 26
**              Power-up delay                             : 2.600 us
**            Stop mode (0)                                : no
**            Stop mode 1                                  : yes
**            ADC mode                                     : Triggered parallel
**            Parallel mode                                : Simultaneous
**            Trigger mode (0)                             : SYNC input or START bit
**            Trigger mode 1                               : SYNC input or START bit
**            DMA trigger source                           : EOSI
**            Differential/Single ended mode               : 
**              ANA0-ANA1                                  : Differential mode
**              ANA2-ANA3                                  : Single ended mode
**              ANB0-ANB1                                  : Single ended mode
**              ANB2-ANB3                                  : Single ended mode
**              ANA4-ANA5                                  : Single ended mode
**              ANA6-ANA7                                  : Single ended mode
**              ANB4-ANB5                                  : Single ended mode
**              ANB6-ANB7                                  : Single ended mode
**            Unipolar/Differential mode                   : 
**              ANA0-ANA1                                  : Fully Differential mode
**              ANA2-ANA3                                  : Fully Differential mode
**              ANB0-ANB1                                  : Fully Differential mode
**              ANB2-ANB3                                  : Fully Differential mode
**              ANA4-ANA5                                  : Fully Differential mode
**              ANA6-ANA7                                  : Fully Differential mode
**              ANB4-ANB5                                  : Fully Differential mode
**              ANB6-ANB7                                  : Fully Differential mode
**            Gain control                                 : 
**              ANA0                                       : x1 amplification
**              ANA1                                       : x1 amplification
**              ANA2                                       : x1 amplification
**              ANA3                                       : x1 amplification
**              ANA4                                       : x1 amplification
**              ANA5                                       : x1 amplification
**              ANA6                                       : x1 amplification
**              ANA7                                       : x1 amplification
**              ANB0                                       : x1 amplification
**              ANB1                                       : x1 amplification
**              ANB2                                       : x1 amplification
**              ANB3                                       : x1 amplification
**              ANB4                                       : x1 amplification
**              ANB5                                       : x1 amplification
**              ANB6                                       : x1 amplification
**              ANB7                                       : x1 amplification
**              Alternative input 0                        : x1 amplification
**              Alternative input 1                        : x1 amplification
**              Alternative input 2                        : x1 amplification
**              Alternative input 3                        : x1 amplification
**            Sample enable                                : 
**              Sample 0                                   : Enabled
**              Sample 1                                   : Enabled
**              Sample 2                                   : Disabled
**              Sample 3                                   : Disabled
**              Sample 4                                   : Disabled
**              Sample 5                                   : Disabled
**              Sample 6                                   : Disabled
**              Sample 7                                   : Disabled
**              Sample 8                                   : Enabled
**              Sample 9                                   : Enabled
**              Sample 10                                  : Disabled
**              Sample 11                                  : Disabled
**              Sample 12                                  : Disabled
**              Sample 13                                  : Disabled
**              Sample 14                                  : Disabled
**              Sample 15                                  : Disabled
**              Sample 16                                  : Disabled
**              Sample 17                                  : Disabled
**              Sample 18                                  : Disabled
**              Sample 19                                  : Disabled
**            Channel to sample mapping                    : 
**              Sample 0                                   : ANA0
**              Sample 1                                   : ANA4
**              Sample 2                                   : ANA2
**              Sample 3                                   : ANA3
**              Sample 4                                   : ANA4
**              Sample 5                                   : ANA5
**              Sample 6                                   : ANA6
**              Sample 7                                   : ANA7
**              Sample 8                                   : ANB0
**              Sample 9                                   : ANB0
**              Sample 10                                  : ANB2
**              Sample 11                                  : ANB3
**              Sample 12                                  : ANB4
**              Sample 13                                  : ANB5
**              Sample 14                                  : ANB6
**              Sample 15                                  : ANB7
**              Sample 16                                  : Alternative input 0
**              Sample 17                                  : Alternative input 1
**              Sample 18                                  : Alternative input 2
**              Sample 19                                  : Alternative input 3
**            Zero crossing                                : 
**              Sample 0                                   : Disabled
**              Sample 1                                   : Disabled
**              Sample 2                                   : Disabled
**              Sample 3                                   : Disabled
**              Sample 4                                   : Disabled
**              Sample 5                                   : Disabled
**              Sample 6                                   : Disabled
**              Sample 7                                   : Disabled
**              Sample 8                                   : Disabled
**              Sample 9                                   : Disabled
**              Sample 10                                  : Disabled
**              Sample 11                                  : Disabled
**              Sample 12                                  : Disabled
**              Sample 13                                  : Disabled
**              Sample 14                                  : Disabled
**              Sample 15                                  : Disabled
**              Sample 16                                  : Disabled
**              Sample 17                                  : Disabled
**              Sample 18                                  : Disabled
**              Sample 19                                  : Disabled
**            Low limit                                    : 
**              Sample 0                                   : 0
**              Sample 1                                   : 0
**              Sample 2                                   : 0
**              Sample 3                                   : 0
**              Sample 4                                   : 0
**              Sample 5                                   : 0
**              Sample 6                                   : 0
**              Sample 7                                   : 0
**              Sample 8                                   : 0
**              Sample 9                                   : 0
**              Sample 10                                  : 0
**              Sample 11                                  : 0
**              Sample 12                                  : 0
**              Sample 13                                  : 0
**              Sample 14                                  : 0
**              Sample 15                                  : 0
**              Sample 16                                  : 0
**              Sample 17                                  : 0
**              Sample 18                                  : 0
**              Sample 19                                  : 0
**            High limit                                   : 
**              Sample 0                                   : 32760
**              Sample 1                                   : 32760
**              Sample 2                                   : 32760
**              Sample 3                                   : 32760
**              Sample 4                                   : 32760
**              Sample 5                                   : 32760
**              Sample 6                                   : 32760
**              Sample 7                                   : 32760
**              Sample 8                                   : 32760
**              Sample 9                                   : 32760
**              Sample 10                                  : 32760
**              Sample 11                                  : 32760
**              Sample 12                                  : 32760
**              Sample 13                                  : 32760
**              Sample 14                                  : 32760
**              Sample 15                                  : 32760
**              Sample 16                                  : 32760
**              Sample 17                                  : 32760
**              Sample 18                                  : 32760
**              Sample 19                                  : 32760
**            Offset                                       : 
**              Sample 0                                   : 0
**              Sample 1                                   : 0
**              Sample 2                                   : 0
**              Sample 3                                   : 0
**              Sample 4                                   : 0
**              Sample 5                                   : 0
**              Sample 6                                   : 0
**              Sample 7                                   : 0
**              Sample 8                                   : 4000
**              Sample 9                                   : 0
**              Sample 10                                  : 0
**              Sample 11                                  : 0
**              Sample 12                                  : 0
**              Sample 13                                  : 0
**              Sample 14                                  : 0
**              Sample 15                                  : 0
**              Sample 16                                  : 0
**              Sample 17                                  : 0
**              Sample 18                                  : 0
**              Sample 19                                  : 0
**            Scan control                                 : 
**              Sample 0                                   : Continue
**              Sample 1                                   : Continue
**              Sample 2                                   : Continue
**              Sample 3                                   : Continue
**              Sample 4                                   : Continue
**              Sample 5                                   : Continue
**              Sample 6                                   : Continue
**              Sample 7                                   : Continue
**              Sample 8                                   : Continue
**              Sample 9                                   : Continue
**              Sample 10                                  : Continue
**              Sample 11                                  : Continue
**              Sample 12                                  : Continue
**              Sample 13                                  : Continue
**              Sample 14                                  : Continue
**              Sample 15                                  : Continue
**              Sample 16                                  : Continue
**              Sample 17                                  : Continue
**              Sample 18                                  : Continue
**              Sample 19                                  : Continue
**            Source of ANA6 input                         : AN
**            Source of ANA7 input                         : AN
**            Source of ANB6 input                         : AN
**            Source of ANB7 input                         : AN
**            High volt. ref. source 0                     : internal
**            Low volt. ref. source 0                      : internal
**            High volt. ref. source 1                     : internal
**            Low volt. ref. source 1                      : internal
**            Auto power-down                              : Disabled
**            Auto standby                                 : Disabled
**          Pins                                           : 
**            ANA0                                         : Enabled
**              Pin                                        : GPIOA0/ANA0/CMPA_IN3/CMPC_O
**              Pin signal                                 : 
**            ANA1                                         : Enabled
**              Pin                                        : GPIOA1/ANA1/CMPA_IN0
**              Pin signal                                 : 
**            ANA2                                         : Disabled
**            ANA3                                         : Disabled
**            ANA4                                         : Enabled
**              Pin                                        : GPIOA4/ANA4/CMPD_IN0
**              Pin signal                                 : 
**            ANA5                                         : Disabled
**            ANA6                                         : Disabled
**            ANA7                                         : Disabled
**            ANB0                                         : Enabled
**              Pin                                        : GPIOB0/ANB0/CMPB_IN3
**              Pin signal                                 : 
**            ANB1                                         : Disabled
**            ANB2                                         : Enabled
**              Pin                                        : GPIOB2/ANB2/VREFHB/CMPC_IN3
**              Pin signal                                 : 
**            ANB3                                         : Disabled
**            ANB4                                         : Disabled
**            ANB5                                         : Disabled
**            ANB6                                         : Disabled
**            ANB7                                         : Disabled
**            Alternative input 0                          : Disabled
**            Alternative input 1                          : Disabled
**            Alternative input 2                          : Disabled
**            Alternative input 3                          : Disabled
**            SYNC0                                        : Enabled
**              Pin                                        : PWM2_TRG0
**              Pin signal                                 : 
**            SYNC1                                        : Disabled
**            High volt. ref. pin 0                        : Disabled
**            Low volt. ref. pin 0                         : Disabled
**            High volt. ref. pin 1                        : Disabled
**            Low volt. ref. pin 1                         : Disabled
**          Interrupts                                     : 
**            Conversion complete (0)                      : 
**              Interrupt                                  : INT_ADC_CC0
**              Interrupt priority                         : disabled
**              ISR Name                                   : 
**              End of scan interrupt                      : Disabled
**              DMA request                                : Disabled
**            Conversion complete 1                        : 
**              Interrupt                                  : INT_ADC_CC1
**              Interrupt priority                         : disabled
**              ISR Name                                   : 
**              End of scan interrupt                      : Disabled
**              DMA request                                : Disabled
**            Scan halted interrupt enable                 : 
**              Sample 0                                   : Disabled
**              Sample 1                                   : Disabled
**              Sample 2                                   : Disabled
**              Sample 3                                   : Disabled
**              Sample 4                                   : Disabled
**              Sample 5                                   : Disabled
**              Sample 6                                   : Disabled
**              Sample 7                                   : Disabled
**              Sample 8                                   : Disabled
**              Sample 9                                   : Disabled
**              Sample 10                                  : Disabled
**              Sample 11                                  : Disabled
**              Sample 12                                  : Disabled
**              Sample 13                                  : Disabled
**              Sample 14                                  : Disabled
**              Sample 15                                  : Disabled
**              Sample 16                                  : Disabled
**              Sample 17                                  : Disabled
**              Sample 18                                  : Disabled
**              Sample 19                                  : Disabled
**            Zero crossing or limit error                 : 
**              Interrupt                                  : INT_ADC_ERR
**              Interrupt priority                         : disabled
**              ISR Name                                   : 
**              Zero crossing interrupt                    : Disabled
**              Low Limit Error Interrupt                  : Disabled
**              High Limit Error Interrupt                 : Disabled
**          Initialization                                 : 
**            Power Down ADC 0                             : No
**            Power Down ADC 1                             : No
**            Enable peripheral clock                      : yes
**            Call Init method                             : yes
**            Utilize after reset values                   : default
**     Contents    :
**         Init - void ADC_Init(void);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file ADC_Config.h                                                  
** @version 01.00
** @brief
**          This file implements the ADC (ADC) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
*/         
/*!
**  @addtogroup ADC_Config_module ADC_Config module documentation
**  @{
*/         

#ifndef ADC_Config_H_
#define ADC_Config_H_

/* MODULE ADC. */

/* ADC_CLIST1: SAMPLE3=3,SAMPLE2=2,SAMPLE1=4,SAMPLE0=0 */
#define ADC_CLIST1_VALUE     0x3240
/* ADC_CLIST2: SAMPLE7=7,SAMPLE6=6,SAMPLE5=5,SAMPLE4=4 */
#define ADC_CLIST2_VALUE     0x7654
/* ADC_CLIST3: SAMPLE11=0x0B,SAMPLE10=0x0A,SAMPLE9=8,SAMPLE8=8 */
#define ADC_CLIST3_VALUE     0xBA88
/* ADC_CLIST4: SAMPLE15=0x0F,SAMPLE14=0x0E,SAMPLE13=0x0D,SAMPLE12=0x0C */
#define ADC_CLIST4_VALUE     0xFEDC
/* ADC_CLIST5: ??=0,??=0,??=0,??=0,SEL_INTERNAL_1=0,SEL_TEMP_1=0,SEL_INTERNAL_0=0,SEL_TEMP_0=0,SAMPLE19=3,SAMPLE18=2,SAMPLE17=1,SAMPLE16=0 */
#define ADC_CLIST5_VALUE     0xE4
/* ADC_ZXCTRL1: ZCE7=0,ZCE6=0,ZCE5=0,ZCE4=0,ZCE3=0,ZCE2=0,ZCE1=0,ZCE0=0 */
#define ADC_ZXCTRL1_VALUE    0x00
/* ADC_ZXCTRL2: ZCE15=0,ZCE14=0,ZCE13=0,ZCE12=0,ZCE11=0,ZCE10=0,ZCE9=0,ZCE8=0 */
#define ADC_ZXCTRL2_VALUE    0x00
/* ADC_ZXCTRL3: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,ZCE19=0,ZCE18=0,ZCE17=0,ZCE16=0 */
#define ADC_ZXCTRL3_VALUE    0x00
/* ADC_LOLIM0: ??=0,LLMT=0,??=0,??=0,??=0 */
#define ADC_LOLIM0_VALUE     0x00
/* ADC_LOLIM1: ??=0,LLMT=0,??=0,??=0,??=0 */
#define ADC_LOLIM1_VALUE     0x00
/* ADC_LOLIM2: ??=0,LLMT=0,??=0,??=0,??=0 */
#define ADC_LOLIM2_VALUE     0x00
/* ADC_LOLIM3: ??=0,LLMT=0,??=0,??=0,??=0 */
#define ADC_LOLIM3_VALUE     0x00
/* ADC_LOLIM4: ??=0,LLMT=0,??=0,??=0,??=0 */
#define ADC_LOLIM4_VALUE     0x00
/* ADC_LOLIM5: ??=0,LLMT=0,??=0,??=0,??=0 */
#define ADC_LOLIM5_VALUE     0x00
/* ADC_LOLIM6: ??=0,LLMT=0,??=0,??=0,??=0 */
#define ADC_LOLIM6_VALUE     0x00
/* ADC_LOLIM7: ??=0,LLMT=0,??=0,??=0,??=0 */
#define ADC_LOLIM7_VALUE     0x00
/* ADC_LOLIM8: ??=0,LLMT=0,??=0,??=0,??=0 */
#define ADC_LOLIM8_VALUE     0x00
/* ADC_LOLIM9: ??=0,LLMT=0,??=0,??=0,??=0 */
#define ADC_LOLIM9_VALUE     0x00
/* ADC_LOLIM10: ??=0,LLMT=0,??=0,??=0,??=0 */
#define ADC_LOLIM10_VALUE    0x00
/* ADC_LOLIM11: ??=0,LLMT=0,??=0,??=0,??=0 */
#define ADC_LOLIM11_VALUE    0x00
/* ADC_LOLIM12: ??=0,LLMT=0,??=0,??=0,??=0 */
#define ADC_LOLIM12_VALUE    0x00
/* ADC_LOLIM13: ??=0,LLMT=0,??=0,??=0,??=0 */
#define ADC_LOLIM13_VALUE    0x00
/* ADC_LOLIM14: ??=0,LLMT=0,??=0,??=0,??=0 */
#define ADC_LOLIM14_VALUE    0x00
/* ADC_LOLIM15: ??=0,LLMT=0,??=0,??=0,??=0 */
#define ADC_LOLIM15_VALUE    0x00
/* ADC_LOLIM216: ??=0,LLMT=0,??=0,??=0,??=0 */
#define ADC_LOLIM216_VALUE   0x00
/* ADC_LOLIM217: ??=0,LLMT=0,??=0,??=0,??=0 */
#define ADC_LOLIM217_VALUE   0x00
/* ADC_LOLIM218: ??=0,LLMT=0,??=0,??=0,??=0 */
#define ADC_LOLIM218_VALUE   0x00
/* ADC_LOLIM219: ??=0,LLMT=0,??=0,??=0,??=0 */
#define ADC_LOLIM219_VALUE   0x00
/* ADC_HILIM0: ??=0,HLMT=0x0FFF,??=0,??=0,??=0 */
#define ADC_HILIM0_VALUE     0x7FF8
/* ADC_HILIM1: ??=0,HLMT=0x0FFF,??=0,??=0,??=0 */
#define ADC_HILIM1_VALUE     0x7FF8
/* ADC_HILIM2: ??=0,HLMT=0x0FFF,??=0,??=0,??=0 */
#define ADC_HILIM2_VALUE     0x7FF8
/* ADC_HILIM3: ??=0,HLMT=0x0FFF,??=0,??=0,??=0 */
#define ADC_HILIM3_VALUE     0x7FF8
/* ADC_HILIM4: ??=0,HLMT=0x0FFF,??=0,??=0,??=0 */
#define ADC_HILIM4_VALUE     0x7FF8
/* ADC_HILIM5: ??=0,HLMT=0x0FFF,??=0,??=0,??=0 */
#define ADC_HILIM5_VALUE     0x7FF8
/* ADC_HILIM6: ??=0,HLMT=0x0FFF,??=0,??=0,??=0 */
#define ADC_HILIM6_VALUE     0x7FF8
/* ADC_HILIM7: ??=0,HLMT=0x0FFF,??=0,??=0,??=0 */
#define ADC_HILIM7_VALUE     0x7FF8
/* ADC_HILIM8: ??=0,HLMT=0x0FFF,??=0,??=0,??=0 */
#define ADC_HILIM8_VALUE     0x7FF8
/* ADC_HILIM9: ??=0,HLMT=0x0FFF,??=0,??=0,??=0 */
#define ADC_HILIM9_VALUE     0x7FF8
/* ADC_HILIM10: ??=0,HLMT=0x0FFF,??=0,??=0,??=0 */
#define ADC_HILIM10_VALUE    0x7FF8
/* ADC_HILIM11: ??=0,HLMT=0x0FFF,??=0,??=0,??=0 */
#define ADC_HILIM11_VALUE    0x7FF8
/* ADC_HILIM12: ??=0,HLMT=0x0FFF,??=0,??=0,??=0 */
#define ADC_HILIM12_VALUE    0x7FF8
/* ADC_HILIM13: ??=0,HLMT=0x0FFF,??=0,??=0,??=0 */
#define ADC_HILIM13_VALUE    0x7FF8
/* ADC_HILIM14: ??=0,HLMT=0x0FFF,??=0,??=0,??=0 */
#define ADC_HILIM14_VALUE    0x7FF8
/* ADC_HILIM15: ??=0,HLMT=0x0FFF,??=0,??=0,??=0 */
#define ADC_HILIM15_VALUE    0x7FF8
/* ADC_HILIM216: ??=0,HLMT=0x0FFF,??=0,??=0,??=0 */
#define ADC_HILIM216_VALUE   0x7FF8
/* ADC_HILIM217: ??=0,HLMT=0x0FFF,??=0,??=0,??=0 */
#define ADC_HILIM217_VALUE   0x7FF8
/* ADC_HILIM218: ??=0,HLMT=0x0FFF,??=0,??=0,??=0 */
#define ADC_HILIM218_VALUE   0x7FF8
/* ADC_HILIM219: ??=0,HLMT=0x0FFF,??=0,??=0,??=0 */
#define ADC_HILIM219_VALUE   0x7FF8
/* ADC_OFFST0: ??=0,OFFSET=0,??=0,??=0,??=0 */
#define ADC_OFFST0_VALUE     0x00
/* ADC_OFFST1: ??=0,OFFSET=0,??=0,??=0,??=0 */
#define ADC_OFFST1_VALUE     0x00
/* ADC_OFFST2: ??=0,OFFSET=0,??=0,??=0,??=0 */
#define ADC_OFFST2_VALUE     0x00
/* ADC_OFFST3: ??=0,OFFSET=0,??=0,??=0,??=0 */
#define ADC_OFFST3_VALUE     0x00
/* ADC_OFFST4: ??=0,OFFSET=0,??=0,??=0,??=0 */
#define ADC_OFFST4_VALUE     0x00
/* ADC_OFFST5: ??=0,OFFSET=0,??=0,??=0,??=0 */
#define ADC_OFFST5_VALUE     0x00
/* ADC_OFFST6: ??=0,OFFSET=0,??=0,??=0,??=0 */
#define ADC_OFFST6_VALUE     0x00
/* ADC_OFFST7: ??=0,OFFSET=0,??=0,??=0,??=0 */
#define ADC_OFFST7_VALUE     0x00
/* ADC_OFFST8: ??=0,OFFSET=0x0800,??=0,??=0,??=0 */
#define ADC_OFFST8_VALUE     0x4000
/* ADC_OFFST9: ??=0,OFFSET=0,??=0,??=0,??=0 */
#define ADC_OFFST9_VALUE     0x00
/* ADC_OFFST10: ??=0,OFFSET=0,??=0,??=0,??=0 */
#define ADC_OFFST10_VALUE    0x00
/* ADC_OFFST11: ??=0,OFFSET=0,??=0,??=0,??=0 */
#define ADC_OFFST11_VALUE    0x00
/* ADC_OFFST12: ??=0,OFFSET=0,??=0,??=0,??=0 */
#define ADC_OFFST12_VALUE    0x00
/* ADC_OFFST13: ??=0,OFFSET=0,??=0,??=0,??=0 */
#define ADC_OFFST13_VALUE    0x00
/* ADC_OFFST14: ??=0,OFFSET=0,??=0,??=0,??=0 */
#define ADC_OFFST14_VALUE    0x00
/* ADC_OFFST15: ??=0,OFFSET=0,??=0,??=0,??=0 */
#define ADC_OFFST15_VALUE    0x00
/* ADC_OFFST216: ??=0,OFFSET=0,??=0,??=0,??=0 */
#define ADC_OFFST216_VALUE   0x00
/* ADC_OFFST217: ??=0,OFFSET=0,??=0,??=0,??=0 */
#define ADC_OFFST217_VALUE   0x00
/* ADC_OFFST218: ??=0,OFFSET=0,??=0,??=0,??=0 */
#define ADC_OFFST218_VALUE   0x00
/* ADC_OFFST219: ??=0,OFFSET=0,??=0,??=0,??=0 */
#define ADC_OFFST219_VALUE   0x00
/* ADC_GC1: GAIN7=0,GAIN6=0,GAIN5=0,GAIN4=0,GAIN3=0,GAIN2=0,GAIN1=0,GAIN0=0 */
#define ADC_GC1_VALUE        0x00
/* ADC_GC2: GAIN15=0,GAIN14=0,GAIN13=0,GAIN12=0,GAIN11=0,GAIN10=0,GAIN9=0,GAIN8=0 */
#define ADC_GC2_VALUE        0x00
/* ADC_GC3: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,GAIN19=0,GAIN18=0,GAIN17=0,GAIN16=0 */
#define ADC_GC3_VALUE        0x00
/* ADC_SCHLTEN: SCHLTEN=0 */
#define ADC_SCHLTEN_VALUE    0x00
/* ADC_SCHLTEN2: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,SCHLTEN=0 */
#define ADC_SCHLTEN2_VALUE   0x00
/* ADC_SCTRL: SC=0 */
#define ADC_SCTRL_VALUE      0x00
/* ADC_SCTRL2: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,SC=0 */
#define ADC_SCTRL2_VALUE     0x00
/* ADC_CAL: SEL_VREFH_B=0,SEL_VREFL_B=0,SEL_VREFH_A=0,SEL_VREFL_A=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
#define ADC_CAL_VALUE        0x00
/* ADC_SDIS: DS=0xFCFC */
#define ADC_SDIS_VALUE       0xFCFC
/* ADC_SDIS2: ??=1,??=1,??=1,??=1,??=1,??=1,??=1,??=1,??=1,??=1,??=1,??=1,DS=0x0F */
#define ADC_SDIS2_VALUE      0xFFFF
/* ADC_PWR2: ??=0,??=0,DIV1=4,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
#define ADC_PWR2_VALUE       0x0400
/* ADC_CTRL3: UPDEN_H=0,UPDEN_L=0,??=0,DMASRC=0,??=0,??=0,??=0,??=0,??=0,??=0 */
#define ADC_CTRL3_VALUE      0x00
/* ADC_CTRL2: DMAEN1=0,STOP1=1,START1=0,SYNC1=1,EOSIE1=0,CHNCFG_H=0,SIMULT=1,DIV0=4 */
#define ADC_CTRL2_VALUE      0x5044
/* ADC_CTRL1: DMAEN0=0,STOP0=0,START0=0,SYNC0=1,EOSIE0=0,ZCIE=0,LLMTIE=0,HLMTIE=0,CHNCFG_L=1,??=0,SMODE=5 */
#define ADC_CTRL1_VALUE      0x1015
/* ADC_PWR: ASB=0,??=0,??=0,??=1,PSTS1=1,PSTS0=1,PUDELAY=0x1A,APD=0,??=1,PD1=0,PD0=0 */
#define ADC_PWR_VALUE        0x1DA4

#define ADC_AUTOINIT

/* END ADC. */
#endif /* #ifndef __ADC_Config_H_ */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
