/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : Cpu.h
**     Project     : TPPFC_MC56F82748_V1.0
**     Processor   : MC56F82748VLH
**     Component   : MC56F82748VLH
**     Version     : Component 01.055, Driver 01.00, CPU db: 3.50.001
**     Datasheet   : MC56F827XXRM Rev.1 Draft A 02/2012
**     Compiler    : CodeWarrior DSP C Compiler
**     Date/Time   : 2022-01-28, 14:02, # CodeGen: 6
**     Abstract    :
**         This file collects Processor Expert components configuration 
**         and interface files.
**     Settings    :
**
**     Contents    :
**         EnableInt   - void Cpu_EnableInt(void);
**         DisableInt  - void Cpu_DisableInt(void);
**         SetWaitMode - void Cpu_SetWaitMode(void);
**         SetStopMode - void Cpu_SetStopMode(void);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file Cpu.h
** @version 01.00
** @brief
**         This file collects Processor Expert components configuration 
**         and interface files.
*/         
/*!
**  @addtogroup Cpu_module Cpu module documentation
**  @{
*/         

#ifndef __Init_Config_H
#define __Init_Config_H
  
/* MODULE Init_Config.h */

/* Processor configuration file */
#include "CPU_Config.h"

/* PinSettings component header file */
#include "Pins1.h"
    
/* Initialization component configuration header file */
#include "ADC_Config.h"
/* Initialization component static header file */
#include "ADC_Init.h"
/* Initialization component generated header file */
#include "ADC.h"
    
/* Initialization component configuration header file */
#include "PWMA_Config.h"
/* Initialization component static header file */
#include "PWMA_Init.h"
/* Initialization component generated header file */
#include "PWMA.h"
    
/* Initialization component configuration header file */
#include "GPIOF_Config.h"
/* Initialization component static header file */
#include "GPIOF_Init.h"
/* Initialization component generated header file */
#include "GPIOF.h"
    
/* Initialization component configuration header file */
#include "GPIOC_Config.h"
/* Initialization component static header file */
#include "GPIOC_Init.h"
/* Initialization component generated header file */
#include "GPIOC.h"
    
/* Initialization component configuration header file */
#include "CMPD_Config.h"
/* Initialization component static header file */
#include "CMPD_Init.h"
/* Initialization component generated header file */
#include "CMPD.h"
    
/* Initialization component configuration header file */
#include "CMPC_Config.h"
/* Initialization component static header file */
#include "CMPC_Init.h"
/* Initialization component generated header file */
#include "CMPC.h"
    
/* Initialization component configuration header file */
#include "CMPB_Config.h"
/* Initialization component static header file */
#include "CMPB_Init.h"
/* Initialization component generated header file */
#include "CMPB.h"
    
/* Initialization component configuration header file */
#include "XBARA_Config.h"
/* Initialization component static header file */
#include "XBARA_Init.h"
/* Initialization component generated header file */
#include "XBARA.h"
    
/* Initialization component configuration header file */
#include "SIM_Config.h"
/* Initialization component static header file */
#include "SIM_Init.h"
/* Initialization component generated header file */
#include "SIM.h"
    
/* Initialization component configuration header file */
#include "XBARB_Config.h"
/* Initialization component static header file */
#include "XBARB_Init.h"
/* Initialization component generated header file */
#include "XBARB.h"
    
/* Initialization component configuration header file */
#include "AOI_Config.h"
/* Initialization component static header file */
#include "AOI_Init.h"
/* Initialization component generated header file */
#include "AOI.h"
    
/* Initialization component configuration header file */
#include "GPIOE_Config.h"
/* Initialization component static header file */
#include "GPIOE_Init.h"
/* Initialization component generated header file */
#include "GPIOE.h"
    
/* Initialization component configuration header file */
#include "QSCI0_Config.h"
/* Initialization component static header file */
#include "QSCI0_Init.h"
/* Initialization component generated header file */
#include "QSCI0.h"
    
/* Initialization component configuration header file */
#include "GPIOD_Config.h"
/* Initialization component static header file */
#include "GPIOD_Init.h"
/* Initialization component generated header file */
#include "GPIOD.h"
    
/* Initialization component configuration header file */
#include "QSCI1_Config.h"
/* Initialization component static header file */
#include "QSCI1_Init.h"
/* Initialization component generated header file */
#include "QSCI1.h"
    
  
#endif /* __Init_Config_H */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
