/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : QSCI1.h
**     Project     : TPPFC_MC56F82748_V1.0
**     Processor   : MC56F82748VLH
**     Component   : Init_QSCI
**     Version     : Component 01.000, Driver 01.00, CPU db: 3.50.001
**     Compiler    : CodeWarrior DSP C Compiler
**     Date/Time   : 2022-01-28, 14:02, # CodeGen: 6
**     Abstract    :
**          This file implements the QSCI (QSCI1) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : QSCI1
**          Device                                         : QSCI1
**          Settings                                       : 
**            Clock setting                                : 
**              Clock rate                                 : Bus clock
**              Baud rate divisor                          : 162
**              Fractional baud rate divisor               : 6
**              Baud rate                                  : 19201.2289 Bd
**            Receiver source                              : TX output (internally)
**            Loop mode                                    : Disabled
**            LIN slave mode                               : Disabled
**            Data format                                  : 8 bits
**            Wake up                                      : by idle line
**            Polarity                                     : normal
**            Parity                                       : none
**            Run in wait mode                             : Enabled
**            Stop mode entry hold off                     : Disabled
**            FIFO settings                                : 
**              Tx FIFO watermark                          : 0
**              Rx FIFO watermark                          : 0
**              FIFO mode                                  : Disabled
**          Pins                                           : 
**            RxD pin allocation                           : Enabled
**              RxD pin                                    : GPIOC12/CANRX/SDA0/RXD1
**              RxD pin signal                             : 
**            TxD pin allocation                           : Enabled
**              TxD pin                                    : GPIOC11/CANTX/SCL0/TXD1
**              TxD pin signal                             : 
**          Interrupts/DMA                                 : 
**            Receiver full                                : 
**              Interrupt                                  : INT_QSCI1_RCV
**              Interrupt priority                         : disabled
**              Receiver full interrupt                    : Disabled
**              ISR Name                                   : FMSTR1_Isr
**            Receiver error                               : 
**              Interrupt                                  : INT_QSCI1_RERR
**              Interrupt priority                         : disabled
**              Receiver error interrupt                   : Disabled
**              ISR Name                                   : 
**            Transmitter complete                         : 
**              Interrupt                                  : INT_QSCI1_TIDLE
**              Interrupt priority                         : disabled
**              Transmitter idle interrupt                 : Disabled
**              ISR Name                                   : 
**            Transmitter ready                            : 
**              Interrupt                                  : INT_QSCI1_TDRE
**              Interrupt priority                         : disabled
**              Transmitter empty interrupt                : Disabled
**              ISR Name                                   : FMSTR1_Isr
**            DMA                                          : 
**              Receiver DMA support                       : Disabled
**              Transmitter DMA support                    : Disabled
**          Initialization                                 : 
**            Enable peripheral clock                      : yes
**            Enable transmitter                           : yes
**            Enable receiver                              : yes
**            Receiver wake up mode                        : normal operation
**            Call Init method                             : yes
**            Utilize after reset values                   : default
**     Contents    :
**         Init - void QSCI1_Init(void);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file QSCI1.h
** @version 01.00
** @brief
**          This file implements the QSCI (QSCI1) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
*/         
/*!
**  @addtogroup QSCI1_module QSCI1 module documentation
**  @{
*/         

#ifndef QSCI1_H_
#define QSCI1_H_

/* MODULE QSCI1. */

#include "QSCI1_Init.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Initialization method user name */
#define QSCI1_Init QSCI1_Init
/* PDD macros peripheral base address parameter */
#define QSCI1_DEVICE QSCI1_BASE_PTR
/*
** ===================================================================
** The interrupt service routine must be implemented by user in one
** of the user modules (see QSCI1.c file for more information).
** ===================================================================
*/
void FMSTR1_Isr(void);
/*
** ===================================================================
** The interrupt service routine must be implemented by user in one
** of the user modules (see QSCI1.c file for more information).
** ===================================================================
*/
void FMSTR1_Isr(void);

#ifdef __cplusplus
}
#endif

/* END QSCI1. */
#endif /* #ifndef __QSCI1_H_ */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
