/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : QSCI0_Config.h
**     Project     : TPPFC_MC56F82748_V1.0
**     Processor   : MC56F82748VLH
**     Component   : Init_QSCI
**     Version     : Component 01.000, Driver 01.00, CPU db: 3.50.001
**     Compiler    : CodeWarrior DSP C Compiler
**     Date/Time   : 2022-01-24, 16:51, # CodeGen: 0
**     Abstract    :
**          This file implements the QSCI (QSCI0) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : QSCI0
**          Device                                         : QSCI0
**          Settings                                       : 
**            Clock setting                                : 
**              Clock rate                                 : Bus clock
**              Baud rate divisor                          : 1302
**              Fractional baud rate divisor               : 1
**              Baud rate                                  : 2399.9232 Bd
**            Receiver source                              : TXD pin
**            Loop mode                                    : Disabled
**            LIN slave mode                               : Disabled
**            Data format                                  : 8 bits
**            Wake up                                      : by idle line
**            Polarity                                     : normal
**            Parity                                       : none
**            Run in wait mode                             : Enabled
**            Stop mode entry hold off                     : Disabled
**            FIFO settings                                : 
**              Tx FIFO watermark                          : 0
**              Rx FIFO watermark                          : 0
**              FIFO mode                                  : Enabled
**          Pins                                           : 
**            RxD pin allocation                           : Enabled
**              RxD pin                                    : GPIOC3/TA0/CMPA_O/RXD0/CLKIN1
**              RxD pin signal                             : 
**            TxD pin allocation                           : Enabled
**              TxD pin                                    : GPIOC2/TXD0/XB_OUT11/XB_IN2/CLKO0
**              TxD pin signal                             : 
**          Interrupts/DMA                                 : 
**            Receiver full                                : 
**              Interrupt                                  : INT_QSCI0_RCV
**              Interrupt priority                         : disabled
**              Receiver full interrupt                    : Disabled
**              ISR Name                                   : 
**            Receiver error                               : 
**              Interrupt                                  : INT_QSCI0_RERR
**              Interrupt priority                         : disabled
**              Receiver error interrupt                   : Disabled
**              ISR Name                                   : 
**            Transmitter complete                         : 
**              Interrupt                                  : INT_QSCI0_TIDLE
**              Interrupt priority                         : disabled
**              Transmitter idle interrupt                 : Disabled
**              ISR Name                                   : 
**            Transmitter ready                            : 
**              Interrupt                                  : INT_QSCI0_TDRE
**              Interrupt priority                         : disabled
**              Transmitter empty interrupt                : Disabled
**              ISR Name                                   : 
**            DMA                                          : 
**              Receiver DMA support                       : Disabled
**              Transmitter DMA support                    : Disabled
**          Initialization                                 : 
**            Enable peripheral clock                      : yes
**            Enable transmitter                           : yes
**            Enable receiver                              : yes
**            Receiver wake up mode                        : normal operation
**            Call Init method                             : yes
**            Utilize after reset values                   : default
**     Contents    :
**         Init - void QSCI0_Init(void);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file QSCI0_Config.h                                                  
** @version 01.00
** @brief
**          This file implements the QSCI (QSCI0) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
*/         
/*!
**  @addtogroup QSCI0_Config_module QSCI0_Config module documentation
**  @{
*/         

#ifndef QSCI0_Config_H_
#define QSCI0_Config_H_

/* MODULE QSCI0. */

#define QSCI0_CLEAR_FLAGS
/* QSCI0_RATE: SBRL=0x0516,FRAC_SBR=1 */
#define QSCI0_RATE_VALUE     0x28B1
/* QSCI0_CTRL3: SBRH=0 */
#define QSCI0_CTRL3_VALUE_1  0x00
#define QSCI0_CTRL3_MASK_1   0xE000
/* QSCI0_CTRL1: LOOP=0,SWAI=0,RSRC=1,M=0,WAKE=0,POL=0,PE=0,PT=0,TEIE=0,TIIE=0,RFIE=0,REIE=0,TE=1,RE=1 */
#define QSCI0_CTRL1_VALUE_1  0x200C
#define QSCI0_CTRL1_MASK_1   0xFFFC
/* QSCI0_CTRL2: TFWM=0,RFWM=0,FIFO_EN=1,LINMODE=0,TDE=0,RDE=0 */
#define QSCI0_CTRL2_VALUE    0x20
#define QSCI0_CTRL2_MASK     0x18EB
/* QSCI0_CTRL3: SHEN=0 */
#define QSCI0_CTRL3_VALUE_2  0x00
#define QSCI0_CTRL3_MASK_2   0x01
/* QSCI0_CTRL1: RWU=0 */
#define QSCI0_CTRL1_VALUE_2  0x00
#define QSCI0_CTRL1_MASK_2   0x02

#define QSCI0_AUTOINIT

/* END QSCI0. */
#endif /* #ifndef __QSCI0_Config_H_ */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
