/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : SIM_Config.h
**     Project     : TPPFC_MC56F82748_V1.0
**     Processor   : MC56F82748VLH
**     Component   : Init_SIM
**     Version     : Component 01.000, Driver 01.00, CPU db: 3.50.001
**     Compiler    : CodeWarrior DSP C Compiler
**     Date/Time   : 2022-01-28, 14:02, # CodeGen: 6
**     Abstract    :
**          This file implements the SIM (SIM) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : SIM
**          Device                                         : SIM
**          Common CPU settings                            : 
**            WAIT disable mode                            : Enabled
**            STOP disable mode                            : Enabled
**            DMA disable mode                             : All modes
**            OnCE clock to core                           : Enabled when core TAP is enabled
**            Reset filter                                 : Disabled
**            CLKIN input                                  : CLKIN0
**            Select master PIT                            : M0S1
**            ADC scan control bits re-ordering            : Disabled
**            Dual speed core clock                        : enabled
**          Power controls                                 : 
**            Regulator 1.2 V standby                      : normal mode
**            Regulator 2.7 V powerdown                    : normal mode
**            Regulator 2.7 V standby                      : normal mode
**            Large regulator standby                      : normal mode
**            LPMODE                                       : Exit
**            VLPMODE                                      : Exit
**          Clock output selectors                         : 
**            CLKOUT divide factor                         : Divide by 1
**            CLKOUT0 select                               : System clock
**            CLKOUT0                                      : Disabled
**            CLKOUT1 select                               : System clock
**            CLKOUT1                                      : Disabled
**          Clock gating control in stop mode              : 
**            GPIOA peripheral clock in stop mode          : Disabled
**            GPIOB peripheral clock in stop mode          : Disabled
**            GPIOC peripheral clock in stop mode          : Disabled
**            GPIOD peripheral clock in stop mode          : Disabled
**            GPIOE peripheral clock in stop mode          : Disabled
**            GPIOF peripheral clock in stop mode          : Disabled
**            Timer channel 0 peripheral clock in stop mode : Disabled
**            Timer channel 1 peripheral clock in stop mode : Disabled
**            Timer channel 2 peripheral clock in stop mode : Disabled
**            Timer channel 3 peripheral clock in stop mode : Disabled
**            MSCAN peripheral clock in stop mode          : Disabled
**            I2C peripheral clock in stop mode            : Disabled
**            QSPI0 peripheral clock in stop mode          : Disabled
**            QSPI1 peripheral clock in stop mode          : Disabled
**            QSCI0 peripheral clock in stop mode          : Disabled
**            QSCI1 peripheral clock in stop mode          : Disabled
**            DACA peripheral clock in stop mode           : Disabled
**            DACB peripheral clock in stop mode           : Disabled
**            Programmable Interval Timer 0 peripheral clock in stop mode : Disabled
**            Programmable Interval Timer 1 peripheral clock in stop mode : Disabled
**            CRC peripheral clock in stop mode            : Disabled
**            Cyclic ADC peripheral clock in stop mode     : Disabled
**            CMPA peripheral clock in stop mode           : Disabled
**            CMPB peripheral clock in stop mode           : Disabled
**            CMPC peripheral clock in stop mode           : Disabled
**            CMPD peripheral clock in stop mode           : Disabled
**            PWMA channel 0 peripheral clock in stop mode : Disabled
**            PWMA channel 1 peripheral clock in stop mode : Disabled
**            PWMA channel 2 peripheral clock in stop mode : Disabled
**            PWMA channel 3 peripheral clock in stop mode : Disabled
**          Clock gating control                           : 
**            GPIOA peripheral clock                       : disabled
**            GPIOB peripheral clock                       : disabled
**            GPIOC peripheral clock                       : enabled
**            GPIOD peripheral clock                       : enabled
**            GPIOE peripheral clock                       : enabled
**            GPIOF peripheral clock                       : enabled
**            Timer channel 0 peripheral clock             : disabled
**            Timer channel 1 peripheral clock             : disabled
**            Timer channel 2 peripheral clock             : disabled
**            Timer channel 3 peripheral clock             : disabled
**            MSCAN peripheral clock                       : disabled
**            I2C peripheral clock                         : disabled
**            QSPI0 peripheral clock                       : disabled
**            QSPI1 peripheral clock                       : disabled
**            QSCI0 peripheral clock                       : enabled
**            QSCI1 peripheral clock                       : enabled
**            DACA peripheral clock                        : disabled
**            DACB peripheral clock                        : disabled
**            Programmable Interval Timer 0 peripheral clock : disabled
**            Programmable Interval Timer 1 peripheral clock : disabled
**            CRC peripheral clock                         : disabled
**            Cyclic ADC peripheral clock                  : enabled
**            CMPA peripheral clock                        : disabled
**            CMPB peripheral clock                        : enabled
**            CMPC peripheral clock                        : enabled
**            CMPD peripheral clock                        : enabled
**            PWMA channel 0 peripheral clock              : enabled
**            PWMA channel 1 peripheral clock              : enabled
**            PWMA channel 2 peripheral clock              : enabled
**            PWMA channel 3 peripheral clock              : disabled
**          Peripheral clock rate                          : 
**            QSCI0 clock rate                             : QSCI0_Bus_clock
**            QSCI1 clock rate                             : QSCI1_Bus_clock
**            TMR clock rate                               : TMR_Bus_clock
**            PWM clock rate                               : PWM_2x_Bus_clock
**            I2C filter clock rate                        : I2C_FILT_Bus_clock
**          Peripheral protection                          : 
**            Power mode control write                     : Off
**            GPIO port D                                  : Off
**            Peripheral clock enable                      : Off
**            GPIO and internal peripheral select          : Off
**          Peripheral select                              : 
**            GPIOA0 pin function                          : alt0
**            GPIOB1 pin function                          : alt0
**            GPIOC0 pin function                          : alt0
**            GPIOC2 pin function                          : TXD0
**            GPIOC3 pin function                          : RXD0
**            GPIOC4 pin function                          : alt0
**            GPIOC5 pin function                          : alt0
**            GPIOC6 pin function                          : alt0
**            GPIOC7 pin function                          : alt0
**            GPIOC8 pin function                          : alt0
**            GPIOC9 pin function                          : alt0
**            GPIOC10 pin function                         : alt3
**            GPIOC11 pin function                         : TXD1
**            GPIOC12 pin function                         : RXD1
**            GPIOC13 pin function                         : alt0
**            GPIOC14 pin function                         : alt1
**            GPIOC15 pin function                         : alt0
**            GPIOE4 pin function                          : alt0
**            GPIOE5 pin function                          : alt0
**            GPIOE6 pin function                          : alt0
**            GPIOE7 pin function                          : alt0
**            GPIOF0 pin function                          : SCK1
**            GPIOF1 pin function                          : alt0
**            GPIOF2 pin function                          : XB_OUT6
**            GPIOF3 pin function                          : XB_OUT7
**            GPIOF4 pin function                          : XB_OUT8
**            GPIOF5 pin function                          : XB_OUT9
**            GPIOF6 pin function                          : alt0
**            GPIOF7 pin function                          : alt0
**            GPIOF8 pin function                          : alt0
**          Internal peripheral select                     : 
**            SCI0 input                                   : GPIO
**            SCI1 input                                   : GPIO
**            TA0 input                                    : GPIO
**            TA1 input                                    : GPIO
**            TA2 input                                    : GPIO
**            TA3 input                                    : GPIO
**          Initialization                                 : 
**            Call Init method                             : yes
**            Utilize after reset values                   : default
**     Contents    :
**         Init - void SIM_Init(void);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file SIM_Config.h                                                  
** @version 01.00
** @brief
**          This file implements the SIM (SIM) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
*/         
/*!
**  @addtogroup SIM_Config_module SIM_Config module documentation
**  @{
*/         

#ifndef SIM_Config_H_
#define SIM_Config_H_

/* MODULE SIM. */

/* SIM_CTRL: RST_FILT=0,DMAEbl=3,OnceEbl=0,STOP_disable=0,WAIT_disable=0 */
#define SIM_CTRL_VALUE       0xC0
#define SIM_CTRL_MASK        0x05EF
/* SIM_MISC0: ADC_SCTRL=0,FAST_MODE=1,CLKINSEL=0,PIT_MSTR=0 */
#define SIM_MISC0_VALUE      0x04
#define SIM_MISC0_MASK       0x0F
/* SIM_PWR: SR12STDBY=0,SR27PDN=0,SR27STDBY=0,LRSTDBY=0 */
#define SIM_PWR_VALUE        0x00
#define SIM_PWR_MASK         0xFF
/* SIM_GPSAL: A0=0 */
#define SIM_GPSAL_VALUE      0x00
#define SIM_GPSAL_MASK       0x01
/* SIM_GPSBL: B1=0 */
#define SIM_GPSBL_VALUE      0x00
#define SIM_GPSBL_MASK       0x04
/* SIM_GPSCL: C7=0,C6=0,C5=0,C4=0,C3=2,C2=0,C0=0 */
#define SIM_GPSCL_VALUE      0x80
#define SIM_GPSCL_MASK       0xF7F1
/* SIM_GPSCH: C15=0,C14=1,C13=0,C12=2,C11=2,C10=3,C9=0,C8=0 */
#define SIM_GPSCH_VALUE      0x12B0
/* SIM_GPSEL: E7=0,E6=0,E5=0,E4=0 */
#define SIM_GPSEL_VALUE      0x00
#define SIM_GPSEL_MASK       0x5500
/* SIM_GPSFL: F7=0,F6=0,F5=1,F4=1,F3=1,F2=1,F1=0,F0=2 */
#define SIM_GPSFL_VALUE      0x0552
/* SIM_GPSFH: F8=0 */
#define SIM_GPSFH_VALUE      0x00
#define SIM_GPSFH_MASK       0x03
/* SIM_IPSn: TA3=0,TA2=0,TA1=0,TA0=0,SCI1=0,SCI0=0 */
#define SIM_IPSn_VALUE       0x00
#define SIM_IPSn_MASK        0x0F03
/* SIM_PCR: SCI0_CR=0,SCI1_CR=0,TMR=0,PWM=1,IIC_FILT=0 */
#define SIM_PCR_VALUE        0x0400
#define SIM_PCR_MASK         0x3E00
/* SIM_CLKOUT: CLKODIV=0,CLKDIS1=1,CLKOSEL1=0,CLKDIS0=1,CLKOSEL0=0 */
#define SIM_CLKOUT_VALUE     0x1020
#define SIM_CLKOUT_MASK      0xF3A7
/* SIM_PCE0: TA0=0,TA1=0,TA2=0,TA3=0,GPIOA=0,GPIOB=0,GPIOC=1,GPIOD=1,GPIOE=1,GPIOF=1 */
#define SIM_PCE0_VALUE       0x1E
#define SIM_PCE0_MASK        0xF07E
/* SIM_PCE1: DACB=0,DACA=0,SCI0=1,SCI1=1,QSPI0=0,QSPI1=0,IIC0=0,MSCAN=0 */
#define SIM_PCE1_VALUE       0x1800
#define SIM_PCE1_MASK        0x7B41
/* SIM_PCE2: CMPA=0,CMPB=1,CMPC=1,CMPD=1,CYCADC=1,CRC=0,PIT0=0,PIT1=0 */
#define SIM_PCE2_VALUE       0x0E80
#define SIM_PCE2_MASK        0x1EAC
/* SIM_PCE3: PWMACH0=1,PWMACH1=1,PWMACH2=1,PWMACH3=0 */
#define SIM_PCE3_VALUE       0xE0
#define SIM_PCE3_MASK        0xF0
/* SIM_SD0: TA0=0,TA1=0,TA2=0,TA3=0,GPIOA=0,GPIOB=0,GPIOC=0,GPIOD=0,GPIOE=0,GPIOF=0 */
#define SIM_SD0_VALUE        0x00
#define SIM_SD0_MASK         0xF07E
/* SIM_SD1: DACB=0,DACA=0,SCI0=0,SCI1=0,QSPI0=0,QSPI1=0,IIC0=0,MSCAN=0 */
#define SIM_SD1_VALUE        0x00
#define SIM_SD1_MASK         0x7B41
/* SIM_SD2: CMPA=0,CMPB=0,CMPC=0,CMPD=0,CYCADC=0,CRC=0,PIT0=0,PIT1=0 */
#define SIM_SD2_VALUE        0x00
#define SIM_SD2_MASK         0x1EAC
/* SIM_SD3: PWMACH0=0,PWMACH1=0,PWMACH2=0,PWMACH3=0 */
#define SIM_SD3_VALUE        0x00
#define SIM_SD3_MASK         0xF0
/* SIM_PWRMODE: ??=0,??=0,??=0,??=0,??=0,??=0,LPMS=0,VLPMS=0,??=0,??=0,??=0,??=0,??=0,??=0,LPMODE=0,VLPMODE=0 */
#define SIM_PWRMODE_VALUE    0x00
/* SIM_PROT: PMODE=0,GDP=0,PCEP=0,GIPSP=0 */
#define SIM_PROT_VALUE       0x00
#define SIM_PROT_MASK        0xFF

#define SIM_AUTOINIT

/* END SIM. */
#endif /* #ifndef __SIM_Config_H_ */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
