/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : XBARB.h
**     Project     : TPPFC_MC56F82748_V1.0
**     Processor   : MC56F82748VLH
**     Component   : Init_XBAR
**     Version     : Component 01.000, Driver 01.00, CPU db: 3.50.001
**     Compiler    : CodeWarrior DSP C Compiler
**     Date/Time   : 2022-01-24, 16:51, # CodeGen: 0
**     Abstract    :
**          This file implements the XBAR (XBARB) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : XBARB
**          Device                                         : XBARB
**          Settings                                       : 
**            Output AOI_Input0A                           : PWM0_TRG0
**            Output AOI_Input0B                           : In11
**            Output AOI_Input0C                           : In12
**            Output AOI_Input0D                           : In0
**            Output AOI_Input1A                           : PWM0_TRG1
**            Output AOI_Input1B                           : In11
**            Output AOI_Input1C                           : In12
**            Output AOI_Input1D                           : In0
**            Output AOI_Input2A                           : In0
**            Output AOI_Input2B                           : In0
**            Output AOI_Input2C                           : In0
**            Output AOI_Input2D                           : In0
**            Output AOI_Input3A                           : In0
**            Output AOI_Input3B                           : In0
**            Output AOI_Input3C                           : In0
**            Output AOI_Input3D                           : In0
**          Interrupts                                     : 
**          Initialization                                 : 
**            Call Init method                             : yes
**            Utilize after reset values                   : default
**     Contents    :
**         Init - void XBARB_Init(void);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file XBARB.h
** @version 01.00
** @brief
**          This file implements the XBAR (XBARB) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
*/         
/*!
**  @addtogroup XBARB_module XBARB module documentation
**  @{
*/         

#ifndef XBARB_H_
#define XBARB_H_

/* MODULE XBARB. */

#include "XBARB_Init.h"

/* Initialization method user name */
#define XBARB_Init XBARB_Init
/* PDD macros peripheral base address parameter */
#define XBARB_DEVICE XBARB_BASE_PTR

/* END XBARB. */
#endif /* #ifndef __XBARB_H_ */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
